### PR TITLE
upgrade scaleway integration

### LINKED ISSUE #45: [Scaleway] discover is not working in PAR1 without public network
Hello !

I'm trying to build this kind of cluster : 

```
     +------------------+Scaleway PAR1+-----+
     |                                      |
     |                                      |
     |                                      |
     |                                      |
     |        +--------------+              |
     |        |   Consul 1   |              |
     |        +--------------+              |
     |                                      |
+----+------+           +----------------+  |
| Jump host |           |    Consul 2    |  |
+----+------+           +----------------+  |
     |                                      |
     |         +-------------+              |
     |         |   Consul 3  |              |
     |         +-------------+              |
     |                                      |
     |                                      |
     |                                      |
     |                                      |
     +--------------------------------------+

```

Here, when Consul server is trying to execute retry_join, I've this kind of message in monitor : 

```
agent: Join LAN: discover-scaleway: Head https://cp-ams1.scaleway.com/servers?: dial tcp 51.15.33.64:443: i/o timeout
2018/06/09 15:33:12 [WARN] agent: Join LAN failed: No servers to join, retrying in 30s
```

That's true, 51.x seems to be a public IP that are not available because as you can see in my quick schema, only Jump Host can access to public.

I don't know why discover is trying to query ams1 server ?

Simple ping seems to be enough to troubleshot  : 
```
root@packer-consul-start1s-2018-06-09-14-47-09:~# ping cp-ams1.scaleway.com
PING cp-ams1.scaleway.com (51.15.33.64) 56(84) bytes of data.
^C



root@packer-consul-start1s-2018-06-09-14-47-09:~# ping cp-par1.scaleway.com
PING cp-par1.scaleway.com (212.47.225.64) 56(84) bytes of data.
64 bytes from 64-225-47-212.int.cloud.online.net (212.47.225.64): icmp_seq=1 ttl=59 time=0.498 ms
64 bytes from 64-225-47-212.int.cloud.online.net (212.47.225.64): icmp_seq=2 ttl=59 time=0.579 ms
^C


root@packer-consul-start1s-2018-06-09-14-47-09:~# ping api.scaleway.com
PING api.scaleway.com (212.47.225.64) 56(84) bytes of data.
64 bytes from 64-225-47-212.int.cloud.online.net (212.47.225.64): icmp_seq=1 ttl=59 time=0.480 ms
64 bytes from 64-225-47-212.int.cloud.online.net (212.47.225.64): icmp_seq=2 ttl=59 time=0.664 ms
^C
```

I think the best may be to use api.scaleway.com, which should be available in all datacenters.

I've tried to look into sources of go-discover. I think we just have to edit this line https://github.com/nicolai86/scaleway-sdk/blob/master/server.go#L196 to use api.scaleway.com (seems to be the same IP than cp.par1.scaleway.com)

I'm OK to test some fixes, but in this case I'll need your help, my last Go code was wrote in 2015... + How to build consul with the fixed discover inside ?

+ ping @nicolai86

Thanks for your help !

### PR DESCRIPTION
**Pull request by nicolai86**
This CR upgrades the scaleway integration to resolve #45 .

Main issue is that the otherwise region-aware Scaleway client executed a all-region fanout to fetch servers. This is a relict from its origins, as a tool to feed the scaleway cli.

I've since removed and restructured the provider heavily.

This change updates the provider integration.

### CODE REVIEW

**Comment by Nainterceptor** [comment]
I've reviewed quickly, I'm not enough good in golang to write a _real_ review. Thanks for your work @nicolai86. 

Just one question : Why not querying api.scaleway.com in place of cp-region.scaleway.com ? Seems to be the same API, but maybe api.scaleway.com will route automatically on the right service ? (If it sound good, maybe it's a further refactoring for your lonely days haha)
In it's a good idea, it will move responsability from library to scaleway DNS.

I still hope to have some advises from scaleway guys...

Thanks you again for your fix, can I tip you a beer on some paypal address ?

**Comment by nicolai86** [comment]
Good points @Nainterceptor !

The Scaleway SDK client is region aware (see computeAPI property); to keep the client consistent we should be using the region exposed by the client.

As the client is used outside of Scaleway networks too we can’t rely on api.scaleway.com. 


I’ll update the sdk with the user agent change; luckily it does not affect functionality at all.

**Comment by nicolai86** [comment]
@Nainterceptor ❤️

**Comment by Nainterceptor** [comment]
Any update from hashicorp people ?

**Comment by nicolai86** [comment]
@pearkes can you take a look? I'd really like to unblock @Nainterceptor

**Comment by pearkes** [comment]
(To clarify -- acceptance tests for scaleaway look good, investigating this vsphere failure in Travis)

**Comment by pearkes** [comment]
FYI rebasing should resolve the vsphere failure.

**Comment by nicolai86** [comment]
@pearkes thank you so much. I've updated the PR.

**Comment by pearkes** [comment]
Thanks!

**Comment by Nainterceptor** [comment]
Thanks both of you ! I've to wait for a release now, I guess

**Pull request merged**
