### PR TITLE
Update tencent version

### LINKED ISSUE #172: tencentcloud dependency seems to be gone
Hello people,

I've just realized that this project depends on an unexpected version of `tencentcloud`: https://github.com/hashicorp/go-discover/blob/master/go.mod#L33 :
```
github.com/tencentcloud/tencentcloud-sdk-go v3.0.83+incompatible
```

The tag `v3.0.83` in their repo seems to be [gone](https://github.com/TencentCloud/tencentcloud-sdk-go/tags). I can **still** build locally because I imagine `https://proxy.golang.org` still has the cached version.  However, it won't build using a configuration like this:

```
GOPROXY="direct"
```

So, I was wondering if you have plans for a new version of `go-discover` using an existing tag for `tencentcloud`? 
In `go-discover` currently there are no tags (I know you are aware) so, a default `v0.0.0` version is used in repos dependent on this one (eg, https://github.com/hashicorp/vault/blob/master/go.mod#L63 )

```
github.com/hashicorp/go-discover v0.0.0-20201029210230-738cb3105cd0
```

Edit:
[go-kms-wrapping](https://github.com/hashicorp/go-kms-wrapping/issues/31) seems to have the same problem. I also created an issue over there.

Thanks a lot

### PR DESCRIPTION
**Pull request by jeffwidman**
Tencent pulled the previous tag of their API and switched to `v1`
starting here: https://github.com/TencentCloud/tencentcloud-sdk-go#%E9%80%9A%E8%BF%87go-get%E5%AE%89%E8%A3%85%E6%8E%A8%E8%8D%90

As a result, currently `go get -d` is complaining in downstream repos,
breaking Dependabot (among other things).

So this fixes that.

Fix #172.

### CODE REVIEW

**Comment by jeffwidman** [comment]
nudge @dnephin @RussellRollins any chance you could look at this? It's breaking our downstream Dependabot builds...

**Comment by RussellRollins** [comment]
Hi @jeffwidman.

I see a few differences locally when checking out your fork and running `go mod tidy`. Do you think you could run tidy and commit the changes?

**Comment by jeffwidman** [comment]
My apologies for the delay, we had a new baby, so I'm just emerging from the fog.

@RussellRollins I ran `go mod tidy` when I put this up, and I just re-ran it to be sure, and I don't see any updates... What version of `go` are you using? I ran it originally with `go` `1.16.3` and just re-ran it with the just released `1.16.5` and neither one mutates `go.sum` at all for me... 

Feel free to add a commit onto this PR with the changes that you're seeing in order to unblock the merge, although for safety you'd probably want to understand _why_ you're seeing changes that I'm not.

**Comment by jeffwidman** [comment]
gentle nudge @RussellRollins 

let me know if anything I can do to move this forward...

**Comment by RussellRollins** [comment]
@jeffwidman I am no longer able to reproduce those differences, so clearly an error between my keyboard and my chair, sorry about that, and thanks for confirming you already tidy'd.

Unfortunately, in terms of getting this merged, we really will need the approval and assistance of someone on @hashicorp/consul. I really don't know much about `go-discover`, I have only interacted with it in terms of working on HashiCorp's CI system.

I know the delay here has been frustrating. One workaround you might attempt in the short term, if you are only dependent on tencent as a transitive dependency is adding a [replace directive](https://golang.org/ref/mod#go-mod-file-replace) to your `go.mod` file. Something like:

```
replace github.com/tencentcloud/tencentcloud-sdk-go v3.0.83+incompatible => github.com/tencentcloud/tencentcloud-sdk-go v1.0.162
```

**Comment by jeffwidman** [comment]
Thanks @RussellRollins. 

Any chance you could nudge someone on @hashicorp/consul team to look at this?

It'd be nice to get this resolved so we don't have to do manual workarounds like `// indirect` pins or using `replace`.

**Comment by jeffwidman** [comment]
@jefferai @RussellRollins any chance one of you could nudge someone on @hashicorp/consul team to take a look at this PR? I come back from paternity leave to find it's still broken 😢 .

**Comment by jeffwidman** [comment]
@eculver @dnephin this PR needs input from the consul team, can you take a look?

**Comment by qbiqing** [comment]
Any update for this? Would be really useful. My current workaround is adding `https://proxy.golang.org` to `GOPROXY`.

**Comment by dhiaayachi** [comment]
Thank you for this contribution @jeffwidman

**Comment by jeffwidman** [comment]
Thanks for merging @dhiaayachi

**Comment by jeffwidman** [comment]
I opened https://github.com/hashicorp/vault/pull/12404 to pull this fix into `vault`.

**Pull request merged**
