### PR TITLE
Add DigitalOcean provider.

### PR DESCRIPTION
**Pull request by andrewsomething**
Hi! Nice to see this broken out into its own package. The command line tool can be very useful on its own.

This PR adds a DigitalOcean provider as well as integration test using Terraform.

One thing I was unsure about, looking at the existing code, was the test packages. They seem to be run against live infrastructure. As I don't know what conditions those are run in, mine assumes the Terraform config provided for the integration test has been used.

Thanks!

### CODE REVIEW

**Comment by magiconair** [comment]
The test packages need some love in terms of consistency but their main purpose is to spin up a cluster of two machines, one of them being tagged and then let the `discover` tool find the tagged machine. After that the infra should be taken down again.

**Comment by andrewsomething** [comment]
Right. That's what I've done with the integration tests under `tests/tf/digitalocean` The bit I was less sure about are the tests like: https://github.com/hashicorp/go-discover/blob/master/provider/gce/gce_discover_test.go

**Comment by magiconair** [comment]
Ah, right. I've just moved those from the original implementation when we didn't have the TF tests. With the TF tests in place they can probably go.

**Comment by kitschysynq** [comment]
+1 for this. What's left before this could get merged?

**Comment by magiconair** [comment]
I'll pick this up once we're done with the work for 1.0.

**Comment by magiconair** [comment]
Merged this with some small fixes.

**Comment by magiconair** [comment]
Thanks!

**Comment by magiconair** [comment]
Please note that I did a force-push of master shortly after merging since I had forgotten to update to prefix the commit messages with `digitalocean: `

**Pull request closed without merging**
