### PR TITLE
provider/triton: Add the ability to discover triton instance IPs

### PR DESCRIPTION
**Pull request by stack72**
This adds the ability to pass tags to the Triton-go SDK and get a list of PrimaryIPs for the instances returned

```
go-discover [triton-provider●●] % discover addrs provider=triton account=test key_id=43:00:2a:9b url=https://us-sw-1.api.joyentcloud.com tag_key=consul-role tag_value=server
Registered providers: [aliyun aws azure digitalocean gce os scaleway softlayer triton]
[DEBUG] discover: Using provider "triton"
[INFO] discover-triton: Account is "test"
[INFO] discover-triton: URL is "https://us-sw-1.api.joyentcloud.com"
192.168.29.39
```

### CODE REVIEW

**Comment by pearkes** [comment]
Thanks for the addition @stack72! Can you help point me in the right place to get creds and an account so we can be able to test this both now and down the road?

**Comment by pearkes** [comment]
Thanks @stack72. One more request for you and then I think we can get this merged. If possible, if you could add some basic Terraform configuration for Triton that spins up the resources required to get the tests to pass (see `test/tf/` directory) that'd be great so we can run CI against this, as with the AWS, GCE, Azure and DigitalOcean providers. 

If not, that is ok, we can still merge it -- but it may not be as easy to support and could stop working down the road as you know 😀. See the recently updated README for more information.

**Comment by stack72** [comment]
@pearkes of course - I will add it for you tomorrow :)

**Comment by stack72** [comment]
hey @pearkes 

I just added Terraform config that allows this to be tested. I get a passing test

```
▶ acctests triton TestAddrs
=== RUN   TestAddrs
2018/04/26 23:57:19 [INFO] discover-triton: Account is "test_acc"
2018/04/26 23:57:19 [INFO] discover-triton: URL is "https://us-sw-1.api.joyentcloud.com"
2018/04/26 23:57:21 [DEBUG] Instance ID: "18eabcf8-fcdc-c0a4-83aa-dc447d4b4c58"
2018/04/26 23:57:21 [DEBUG] Instance PrimaryIP: "165.225.156.96"
--- PASS: TestAddrs (2.23s)
PASS
ok  	github.com/hashicorp/go-discover/provider/triton	2.257s
```

Let me know if there are any issues - sorry it took a little longer!

**Pull request merged**
