### PR TITLE
Pull in latest go-autorest/azure-sdk-for-go

### PR DESCRIPTION
**Pull request by tvon**
This is primarily to get support for user assigned MSIs (since go-autorest ~ `v12.1.0`).

### CODE REVIEW

**Comment by tvon** [comment]
Well, I suppose test failures were expected.

**Comment by mkeeler** [comment]
Most of the tests require credentials for the various cloud providers so they wont work on forked repos. However I just pushed your branch to the pr-139 branch and CI is now running for that.

**Comment by mkeeler** [comment]
Assuming the azure tests all pass I think it should be safe to merge this.

**Comment by mkeeler** [comment]
Thanks for the PR.

**Pull request merged**
