### PR TITLE
Add Aliyun(Alibaba Cloud) provider

### PR DESCRIPTION
**Pull request by chacha403**
This PR adds the Aliyun provider.

### CODE REVIEW

**Comment by chacha403** [comment]
**access_key_secret**  is the official name of Aliyun, it has the same meaning as   "secret_access_key" of AWS

**Comment by magiconair** [comment]
Merged it manually with some small tweaks and re-ordering.

Closing #16

**Comment by magiconair** [comment]
Thank you!

**Comment by magiconair** [comment]
@chacha403 I've just noticed something

The docs say that `region` is optional but the code doesn't.

```go
...
    region:            The Aliyun region. Default to region of instance.

...

	if region == "" {
		l.Printf("[DEBUG] discover-aliyun: Region not provided")
		return nil, fmt.Errorf("discover-aliyun: invalid region")
	}
```

Can you provide a follow-up PR which either fixes the docs or the implementation?

**Comment by chacha403** [comment]
@magiconair  will fix it later

**Pull request closed without merging**
