### PR TITLE
Add Aliyun(Alibaba Cloud) provider

### PR DESCRIPTION
**Pull request by chacha403**
Hi!  I'm deploying consul on Aliyun(Alibaba Cloud) and thought that would be nice to use the cloud metadata to perform the join between instances. 
This PR adds the Aliyun provider.

### CODE REVIEW

**Comment by magiconair** [comment]
Thanks for the PR!

Could you please update the PR as follows:

* rebase the commit and squash the code into a single commit
* add the missing dependencies like in a separate commit since we don't use submodules
* run `github.com/magiconair/vendorfmt` on the `vendor.json` file 
* lowercase the commit messages and prefix them with `aliyun: `
* maybe rename `access_key_secret` to `secret_access_key` since we're using that for the other providers unless this is the official name for the secret

**Comment by magiconair** [comment]
Hi @chacha403, this doesn't look like it has been rebased properly. Can you do a `git rebase master` and then a `git push -f`?

Thx

**Comment by chacha403** [comment]
Yep. I am newbie and found made a mistake

**Comment by magiconair** [comment]
@chacha403 no worries :)

**Comment by chacha403** [comment]
I've make another PR, would u close this one?

**Comment by magiconair** [comment]
Superseded by #16.

**Pull request closed without merging**
