### PR TITLE
Use Dockerhub Mirror

### PR DESCRIPTION
**Pull request by RussellRollins**
Dockerhub is going to start rate limiting unauthenticated pulls.

### CODE REVIEW

**Comment by ncabatoff** [comment]
I thought I read that
> CircleCI entered into an agreement with Dockerhub so pulls for circleci and cimg images hosted on Dockerhub will not require auth

?

**Comment by RussellRollins** [comment]
@ncabatoff Circle has [changed their story](https://support.circleci.com/hc/en-us/articles/360050623311-Docker-Hub-rate-limiting-FAQ) on this a few times.

>I use CircleCI convenience images, does this affect me?
>
> No, as mentioned previously CircleCI has partnered with Docker to ensure that our users can continue to access Docker Hub without rate limits.
>
> However, these rate limits may go into effect for CircleCI users in the future. That’s why we’re encouraging you and your team to add Docker Hub authentication to your CircleCI configuration and consider upgrading your Docker Hub plan, as appropriate, to prevent any impact from rate limits in the future.

It does seem like _maybe_ at the rollout of pull limits, we will be fine, but they're extremely non-committal about that being the case long term.

Our plan is to move all executor images to point to the mirror, if you would prefer not to do so for this project, that's fine as well, but I don't think it's safe to assume Circle will prevent rate limiting forever.

**Comment by ncabatoff** [comment]
Oh I don't object to the change, just trying to confirm whether this is necessary for other projects too.  Thanks for the extra details.

**Review by dnephin — APPROVED** [review]
LGTM, provider test failures look unrelated

**Pull request merged**
