### PR TITLE
Fix aliyun provider issue #183

### PR DESCRIPTION
**Pull request by peczenyj**
update DescribeInstancesWithRaw to use `ecs.TagType`

this fix issue #183

### CODE REVIEW

**Comment by peczenyj** [comment]
fixes #183

**Comment by peczenyj** [comment]
"You have signed the CLA for multiple repositories or organizations" ... waiting

**Comment by Yamakaky** [comment]
Is something blocking the merge? What can we do to advance it?

**Comment by peczenyj** [comment]
I think they just don't want ...

**Comment by peczenyj** [comment]
ok I no one is interested on this, I will close it

**Comment by peczenyj** [comment]
ok, since no one seems interested on this PR I will close it

have a good day

**Pull request closed without merging**
