### PR TITLE
AWS: Added option to discover IPv6 and public IPv4

### PR DESCRIPTION
**Pull request by burdandrei**

### CODE REVIEW

**Comment by magiconair** [comment]
That's a good addition but I'm not so fond of the name for the option. Maybe `iftype={ipv4,ipv6}` or `addrtype={privateV4,publicV6}` This would give us more options in the future.

**Comment by burdandrei** [comment]
I thought about it, and wanted to add public ip as well, i like the `addrtype` name
how about `addrtype={privatev4,publicv4,publicv6}` ?

**Comment by magiconair** [comment]
better

**Comment by magiconair** [comment]
but we're using snake case for the other options. How about `addrtype=private_v4,public_v4,public_v6`

**Comment by burdandrei** [comment]
awesome! doing it now!

**Comment by burdandrei** [comment]
Done!

**Comment by magiconair** [comment]
I've made a small change from `addrtype` to `addr_type` to make the key name consistent with the rest.

**Comment by magiconair** [comment]
Thanks for providing this!

**Comment by burdandrei** [comment]
Happy it's in! I saw you closed  documentation pull request to consul. is it autogenerated from here?

**Comment by magiconair** [comment]
ah, darn. I'll add it. Thx for reminding me.

**Comment by magiconair** [comment]
Done: https://www.consul.io/docs/agent/options.html#amazon-ec2

**Pull request closed without merging**
